name: qBroadcast
version: '${version}'
main: me.qmaan.Main
api-version: '1.13'
authors: [qmaan]
commands:
  qbroadcast:
    aliases:
      - qbc
      - qbcast
  broadcast:
    aliases:
      - bc
      - bcast
      - ad