name: qBroadcast
version: '${version}'
main: me.qmaan.Main
api-version: '1.13'
authors: [qmaan]
commands:
  broadcast:
    permisson: broadcast.use
    children:
      broadcast.reload:
        permisson: broadcast.reload
    permissions: qbc.use
    aliases:
      - bc
      - bcast
      - ad